### ISSUE TITLE
Problems adding the <font> label

### ISSUE THREAD

**Issue by carloshurtado** [mariosky/protoboard#33]
When i try to add the <font color="blue"> label in the section Instrucciones del ejercicio it autocompletes and works fine, but when i save it the color doesn't change and displays the label. After checking Instrucciones del ejercicio again i get this text:  &lt;font color="blue"&gt;System.out.println();&lt;/font&gt;

**Comment by mariosky** [comment]
Use the appropriate class or element:  text-success, pre, code, etc.    Font will open the door to too many styles.
